### PR TITLE
Add project modules

### PR DESCRIPTION
**Pull request by arsonistAnt**
Add the initial modules for the android app.

blocked by https://github.com/arsonistAnt/bjj-app/pull/2

### CODE REVIEW

**Review by kimsaehun — COMMENTED** [review]
I think you took the wrong side when merging. I believe you want to add back in the includes.

**Comment by arsonistAnt** [comment]
@kimsaehun Hey thanks, you suck.

**Review by tn-tran — APPROVED** [review]
Good job

**Comment by kimsaehun** [comment]
@arsonistAnt At least I didn't suck out the code.

**Pull request merged**
