### PR TITLE
front-end/add_badge_mockup

### PR DESCRIPTION
**Pull request by tn-tran**
Added badges as belts
Thoughts? 

Screen Shot 2022-05-23 at 4 01 34 PM

### CODE REVIEW

**Comment by arsonistAnt** [comment]
@tn-tran Oh shit thats sick, do all the belts have a black stripe? I'm fine with going with this approach, i'll have to update my badge component then. Where can i look at different belt types?

**Comment by arsonistAnt** [comment]
I do like the colors but how would it look over a dark gray theme background, since we're copying that pokemon app the main color background is quite dark.

**Comment by tn-tran** [comment]
@arsonistAnt Yup. To advance the next color, they need to earn 4 'stripes'. I might include stripes if we need more badges.

Screen Shot 2022-05-23 at 4 40 10 PM

**Comment by tn-tran** [comment]
> I do like the colors but how would it look over a dark gray theme background, since we're copying that pokemon app the main color background is quite dark.

I say in that case, add the white stripes for each belt, white text, and a border over the belt.

**Comment by arsonistAnt** [comment]
@tn-tran That sounds like it would work, could you provide a visual example? 🤔

**Comment by tn-tran** [comment]
> @tn-tran That sounds like it would work, could you provide a visual example? 🤔

Something like this

Screen Shot 2022-05-24 at 10 16 53 AM

**Comment by tn-tran** [comment]
These flairs from the [BJJ subreddit](https://reddit.com/r/bjj/) look nice. Maybe something like that? We can use the drawings as large buttons. 

Screen Shot 2022-05-24 at 10 46 31 AM
Screen Shot 2022-05-24 at 10 46 21 AM

**Comment by arsonistAnt** [comment]
@tn-tran I really like this one, lets stick to this?

> > @tn-tran That sounds like it would work, could you provide a visual example? 🤔
> 
> Something like this
> 
> Screen Shot 2022-05-24 at 10 16 53 AM

**Review by arsonistAnt — APPROVED** [review]

**Pull request merged**
